# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0002_color_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='user_insert',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_insert_currency', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='user_update',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_currency', to=settings.AUTH_USER_MODEL),
        ),
    ]
