# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0003_auto_20180106_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.CurrencyDescription'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='user_insert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_insert_currency', to=settings.AUTH_USER_MODEL),
        ),
    ]
