# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20180106_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='owners',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
