# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20180106_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
