# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_currencyrate_currencyrateline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrateline',
            name='value',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
