# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_auto_20180208_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='utils.Currency'),
        ),
    ]
