# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_auto_20180329_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='bg_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
