# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='starting_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
