# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountowner',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountowner',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='accountowner',
            name='user_insert',
        ),
        migrations.RemoveField(
            model_name='accountowner',
            name='user_update',
        ),
        migrations.AddField(
            model_name='account',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AccountOwner',
        ),
    ]
