# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyuser',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utils.Currency'),
            preserve_default=False,
        ),
    ]
