# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_account_starting_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Color'),
        ),
    ]
