# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20171225_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='payee',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
