# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_currencyuser_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='type_account',
            new_name='account_type',
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Currency'),
        ),
    ]
