# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20171129_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountowner',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
    ]
