# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0003_auto_20171229_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payee', models.CharField(blank=True, max_length=128, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(upload_to=b'transactions')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Account')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.SubCategory')),
                ('trx_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.TransactionType')),
                ('user_insert', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_insert_transaction', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='trx_type',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='user_insert',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='user_update',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
