# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('budget', '0004_auto_20171229_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utils.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
