# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_auto_20180116_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetdetail',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='budget.Budget'),
        ),
    ]
