# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_auto_20180121_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodtype',
            name='code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
