# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_auto_20180122_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodtype',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
