# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0017_auto_20180129_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='user_insert',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='user_update',
        ),
        migrations.AddField(
            model_name='category',
            name='user_insert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_insert_category', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='user_update',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
