# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_auto_20180201_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
