# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0021_budget_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetdetail',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='budgetdetail',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='budgetdetail',
            name='category',
        ),
        migrations.DeleteModel(
            name='BudgetDetail',
        ),
    ]
