# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0022_auto_20180201_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetline',
            name='budget',
        ),
        migrations.AddField(
            model_name='budgetline',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='budget.BudgetPeriod'),
            preserve_default=False,
        ),
    ]
