# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0023_auto_20180201_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetYear'),
        ),
    ]
