# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0027_auto_20180205_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyuser',
            name='inverse_ratio',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currencyuser',
            name='ratio',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
