# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0029_auto_20180208_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetShareMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='budget.Budget')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetShareStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='budgetsharemember',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetShareStatus'),
        ),
    ]
