# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0031_auto_20180227_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetsharemember',
            name='id',
        ),
        migrations.AddField(
            model_name='budgetsharemember',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
