# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_auto_20180208_1920'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0032_auto_20180227_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayShedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('value', models.IntegerField()),
                ('user_insert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_insert_dayshedule', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_dayshedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurrentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RecurrentShedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_posting', models.DateField(blank=True, null=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.DayShedule')),
                ('period_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.PeriodType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurrentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange', models.DecimalField(decimal_places=2, max_digits=10)),
                ('place', models.CharField(blank=True, max_length=128, null=True)),
                ('payee', models.CharField(blank=True, max_length=128, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=b'transactions')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Currency')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.SubCategory')),
                ('trx_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.TransactionType')),
                ('user_insert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_insert_recurrenttransaction', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_recurrenttransaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recurrentshedule',
            name='recurrent_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.RecurrentTransaction'),
        ),
        migrations.AddField(
            model_name='recurrentshedule',
            name='user_insert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_insert_recurrentshedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurrentshedule',
            name='user_update',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_recurrentshedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurrenthistory',
            name='recurrent_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.RecurrentTransaction'),
        ),
    ]
