# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0033_auto_20180317_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrenttransaction',
            name='exchange',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
