# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0034_auto_20180317_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrentshedule',
            name='period_type',
        ),
        migrations.AddField(
            model_name='dayshedule',
            name='period_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.PeriodType'),
            preserve_default=False,
        ),
    ]
