# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0035_auto_20180317_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrentshedule',
            name='recurrent_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shedule', to='budget.RecurrentTransaction'),
        ),
    ]
