# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0037_auto_20180318_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayshedule',
            name='value',
            field=models.CharField(max_length=10),
        ),
    ]
