# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0039_auto_20180318_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrentSheduleLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('et_date', models.DateField()),
                ('log_date', models.DateField()),
                ('recurrent_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shedule_lines', to='budget.RecurrentTransaction')),
            ],
        ),
    ]
