# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0042_remove_recurrentshedule_is_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurrentsheduleline',
            old_name='recurrent_transaction',
            new_name='recurrent',
        ),
    ]
