# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0043_auto_20180322_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrentsheduleline',
            name='recurrent',
        ),
        migrations.AddField(
            model_name='recurrentsheduleline',
            name='shedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shedule_lines', to='budget.RecurrentShedule'),
            preserve_default=False,
        ),
    ]
