# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0045_auto_20180322_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrentsheduleline',
            name='log_date',
        ),
        migrations.AddField(
            model_name='recurrentsheduleline',
            name='log_post_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
