# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0046_auto_20180322_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_account',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
