# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_auto_20180208_1920'),
        ('budget', '0047_transaction_amount_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Currency'),
        ),
    ]
