# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-01 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0048_budget_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_account',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
