# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0049_auto_20180401_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=b'banks')),
                ('user_insert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_insert_bank', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_bank', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('extention', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FormatDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_pos_date', models.CharField(max_length=1)),
                ('field_pos_amount', models.CharField(max_length=1)),
                ('field_pos_description', models.CharField(max_length=1)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Bank')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.FileType')),
                ('format_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.FormatDate')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionUploaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Account')),
                ('user_insert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_insert_transactionuploaded', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_transactionuploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Bank'),
        ),
    ]
