# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0051_auto_20180406_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefile',
            name='field_post_trans_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='templatefile',
            name='income_char',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='templatefile',
            name='spend_char',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='templatefile',
            name='field_pos_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='templatefile',
            name='field_pos_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='templatefile',
            name='field_pos_description',
            field=models.IntegerField(default=0),
        ),
    ]
