# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0054_auto_20180406_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatdate',
            name='split_char',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
