# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0055_formatdate_split_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionuploaded',
            name='trx_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.TransactionType'),
            preserve_default=False,
        ),
    ]
