# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0056_transactionuploaded_trx_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionuploaded',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.SubCategory'),
        ),
    ]
