# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0057_transactionuploaded_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoryByDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.SubCategory')),
            ],
        ),
    ]
