# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 14:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0058_subcategorybydescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorybydescription',
            name='user_insert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_insert_subcategorybydescription', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategorybydescription',
            name='user_update',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_subcategorybydescription', to=settings.AUTH_USER_MODEL),
        ),
    ]
