# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0059_auto_20180410_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatefile',
            old_name='field_post_trans_type',
            new_name='field_pos_trans_type',
        ),
    ]
