# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0060_auto_20180410_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefile',
            name='field_pos_referencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactionuploaded',
            name='reference',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
