# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0061_auto_20180411_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatefile',
            old_name='field_pos_referencia',
            new_name='field_pos_reference',
        ),
    ]
